from .hub_client import HubClient

# ── Recon Agent ───────────────────────────────────────────────────────────────

RECON_TOOLS = [
    {
        'type': 'function',
        'name': 'query_database',
        'description': (
            'Execute a read-only SQL query or a meta command against the warehouse SQLite database. '
            'Supported: SELECT ..., SHOW TABLES, SHOW CREATE TABLE <name>.'
        ),
        'parameters': {
            'type': 'object',
            'properties': {
                'query': {
                    'type': 'string',
                    'description': 'SQL query or meta command, e.g. "SHOW TABLES" or "SELECT * FROM users".',
                }
            },
            'required': ['query'],
        },
    },
    {
        'type': 'function',
        'name': 'generate_signature',
        'description': (
            'Generate a SHA1 signature for an order. '
            'Requires the login and birthday of the transport user and the numeric destination_id of the city.'
        ),
        'parameters': {
            'type': 'object',
            'properties': {
                'login': {
                    'type': 'string',
                    'description': 'Login of the user creating the order.',
                },
                'birthday': {
                    'type': 'string',
                    'description': 'Birthday of the user in YYYY-MM-DD format.',
                },
                'destination': {
                    'type': 'integer',
                    'description': 'Numeric destination_id of the target city.',
                },
            },
            'required': ['login', 'birthday', 'destination'],
        },
    },
]

# ── Orders Agent ──────────────────────────────────────────────────────────────

ORDERS_TOOLS = [
    {
        'type': 'function',
        'name': 'create_order',
        'description': 'Create a new warehouse order for a city. Returns the order id on success.',
        'parameters': {
            'type': 'object',
            'properties': {
                'title': {'type': 'string', 'description': 'Human-readable title for the order.'},
                'creator_id': {'type': 'integer', 'description': 'user_id of the transport user.'},
                'destination': {'type': 'integer', 'description': 'Numeric destination_id of the target city.'},
                'signature': {'type': 'string', 'description': 'SHA1 signature generated by signatureGenerator.'},
            },
            'required': ['title', 'creator_id', 'destination', 'signature'],
        },
    },
    {
        'type': 'function',
        'name': 'append_items',
        'description': (
            'Add items to an existing order in batch. '
            'Pass items as a dict mapping item name to quantity, e.g. {"woda": 120, "chleb": 45}.'
        ),
        'parameters': {
            'type': 'object',
            'properties': {
                'order_id': {'type': 'string', 'description': 'ID of the order returned by create_order.'},
                'items': {
                    'type': 'object',
                    'description': 'Mapping of item name to integer quantity.',
                    'additionalProperties': {'type': 'integer'},
                },
            },
            'required': ['order_id', 'items'],
        },
    },
    {
        'type': 'function',
        'name': 'submit_done',
        'description': (
            'Submit all orders for final verification. '
            'Call this only after all city orders are created and filled. '
            'Returns the flag on success.'
        ),
        'parameters': {'type': 'object', 'properties': {}, 'required': []},
    },
]


def make_recon_handlers(hub: HubClient) -> dict:
    def query_database(query: str) -> dict:
        return hub.query_database(query)

    def generate_signature(login: str, birthday: str, destination: int) -> dict:
        return hub.generate_signature(login=login, birthday=birthday, destination=destination)

    return {
        'query_database': query_database,
        'generate_signature': generate_signature,
    }


def make_orders_handlers(hub: HubClient) -> dict:
    def create_order(title: str, creator_id: int, destination: int, signature: str) -> dict:
        resp = hub.create_order(
            title=title,
            creator_id=creator_id,
            destination=destination,
            signature=signature,
        )
        order = resp.get('order', {})
        return {'id': order.get('id'), 'code': resp.get('code'), 'message': resp.get('message')}

    def append_items(order_id: str, items: dict) -> dict:
        return hub.append_items(order_id=order_id, items=items)

    def submit_done() -> dict:
        return hub.done()

    return {
        'create_order': create_order,
        'append_items': append_items,
        'submit_done': submit_done,
    }
